添加答题功能与支持需解锁章节的课程
Samueli924/chaoxing pull request #360
Opened 2024-10-18 05:07 UTC by sz134055

添加答题功能与支持需解锁章节的课程
- 添加题库模块，已支持言溪题库(https://tk.enncy.cn/)，更多题库可以自行模范实现
- 题库支持本地缓存
- 支持章节需解锁的课程

2024-10-18 06:07 UTC, Samueli924 commented on main.py
> +                        logger.trace(f"识别到章节检测任务, 任务章节: {course['title']}")
添加一个命令行参数，默认关闭，加到README里。experiment实验功能判断是否开启，如果开启则尝试完成章节检测

2024-10-18 06:08 UTC, Samueli924 reviewed
感谢帮助，代码非常好

2024-10-18 06:10 UTC, Samueli924 requested changes
我建议把完成章节检测作为一个实验性功能，默认是关闭状态，通过在命令行加experimental参数开启，在关闭状态时遇到workid还是默认continue跳过比较好。

2024-10-18 06:48 UTC, sz134055 commented
> 我建议把完成章节检测作为一个实验性功能，默认是关闭状态，通过在命令行加experimental参数开启，在关闭状态时遇到workid还是默认continue跳过比较好。

有些课程当前章节不完成是没办法获取到下一章节的，不配置题库视为不答题，会自动跳过的，在学习方法`Chaoxing().study_work()`里开头进行了判断，相当于实现了你说的跳过吧
```python
if self.tiku.DISABLE or not self.tiku:
            return None
```

2024-10-20 08:21 UTC, sz134055 commented
感觉没什么好修复好更新的了（~~因为我刷完了~~），个别不支持的任务基本也是非任务点，且点进去就算完成，懒得找API跟进了。
不过感觉可以弄个Dockerfile。

2024-10-21 01:52 UTC, Samueli924 approved these changes
感谢帮助！已合并提交代码

2024-10-21 01:52 UTC, merged

2024-12-06 17:12 UTC, tooplick commented
哥可以帮我弄个这个题库嘛，研究了好长时间，还是不会，呜呜呜https://q.icodef.com/

2024-12-17 16:54 UTC, Jaggersqewsd commented
怎么添加题库啊？？谁可以教我一下有偿QQ2160489511

2024-12-19 06:38 UTC, sz134055 commented
> 怎么添加题库啊？？谁可以教我一下有偿QQ2160489511

现在有人实现了[tikuAdapter](https://github.com/DokiDoki1103/tikuAdapter)，支持多个题库。
如果你想要的不在里面，那就按下面的步骤写你自己的题库类：
你的题库类需要继承Tiku类，然后至少实现：
- `_query()`：在本地题库缓存里匹配不到的时候会调用该方法，即从你实现的题库中查询。
- `_init_tiku()`：用来初始化题库的，比如你的题库查询接口可能需要token之类的。

可以在配置文件里[tiku]下追加配置项。要启用你的题库就需要填写provider=你的题库类名（大小写一致）