添加自动编译action和检查更新功能
Samueli924/chaoxing pull request #88
Opened 2022-04-19 08:32 UTC by lyj0309

2022-04-19 12:07 UTC, huajijam commented
请自行rebase再进行pr

2022-04-19 12:20 UTC, huajijam requested changes

2022-04-19 12:20 UTC, huajijam commented on .github/workflows/main.yml
> +  push:
```suggestion
```

just use work_dispatch

2022-04-19 12:23 UTC, huajijam commented on utils/functions.py
> +        resp = requests.get("https://api.github.com/repos/Samueli924/chaoxing/releases/latest").json()
并不推荐启用默认检查更新，这约等于强奸用户，且极大程度上降低运行效率

2022-04-19 12:27 UTC, huajijam commented on .github/workflows/main.yml
> +            name: 'macos64'
```suggestion
```
this project doesn't need these architectures

2022-04-20 02:01 UTC, closed without merging

2022-04-20 02:40 UTC, lyj0309 commented on utils/functions.py
> +        resp = requests.get("https://api.github.com/repos/Samueli924/chaoxing/releases/latest").json()
> 并不推荐启用默认检查更新，这约等于强奸用户，且极大程度上降低运行效率

哪有啥好的解决方案吗，进去的时候问用户是否检查更新还是啥呢，github-api的服务器和github的不一样，是sg的azure，我测试全国3网都是绿的，响应在1s以内

详情https://www.boce.com/http/api.github.com

2022-10-11 07:41 UTC, huajijam commented
不作干预就是最好的办法

lyj ***@***.***> 于 2022年4月20日周三 10:40写道：

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In utils/functions.py
> <https://github.com/Samueli924/chaoxing/pull/88#discussion_r853678996>:
>
> > @@ -30,10 +32,28 @@ def title_show(logo):
>
>          print("\n" + "-"*120)
>
>      else:
>
>          print("\n")
>
> -    print("欢迎使用Samueli924/chaoxing\n对代码有任何疑问或建议，请前往https://github.com/Samueli924/chaoxing进行反馈")
>
> +    print("欢迎使用Samueli924/chaoxing",end="")
>
> +    try:
>
> +        ver = get_ver()
>
> +        print(" v"+ver)
>
> +        print("正在检查更新···", end="")
>
> +        resp = requests.get("https://api.github.com/repos/Samueli924/chaoxing/releases/latest").json()
>
>
> 并不推荐启用默认检查更新，这约等于强奸用户，且极大程度上降低运行效率
>
>
> 哪有啥好的解决方案吗，进去的时候问用户是否检查更新还是啥呢，github-api的服务器和github的不一样，是sg的azure，我测试全国3网都是绿的，响应在1s以内
>
> 详情https://www.boce.com/http/api.github.com
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Samueli924/chaoxing/pull/88#discussion_r853678996>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AG65LQWBTPMOGCZSNUQLGODVF5VCZANCNFSM5TYCASIQ>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>